In [1]:
import os
import pandas as pd

In [2]:
using_Google_colab = False
using_Anaconda_on_Mac_or_Linux = True
using_Anaconda_on_windows = False

In [3]:
if using_Google_colab:
    from google.colab import drive
    drive.mount('/content/drive')

In [4]:
if using_Google_colab:
    dir_input = "/content/drive/MyDrive/COVID_Project/input"
if using_Anaconda_on_Mac_or_Linux:
    dir_input = "../input"
if using_Anaconda_on_windows:
    dir_input = r"..\input"

## PD3.1		Open Notebook titled “Reformat_operation - Activity 1”

Read file

In [5]:
df_confirmed_cases = pd.read_csv(os.path.join(dir_input, "USA_Facts", "covid_confirmed_usafacts.csv"))
df_confirmed_cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2022-01-18,2022-01-19,2022-01-20,2022-01-21,2022-01-22,2022-01-23,2022-01-24,2022-01-25,2022-01-26,2022-01-27
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,12738,12833,12928,13019,13019,13019,13251,13251,13251,13251
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,47143,47662,48338,49168,49168,49168,50313,50313,50313,50313
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,4741,4800,4843,4902,4902,4902,5054,5054,5054,5054
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,5385,5486,5565,5663,5663,5663,5795,5795,5795,5795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,9082,9184,9241,9449,9449,9449,9609,9712,9810,10007
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,8531,8638,8741,8814,8814,8814,8960,9049,9121,9195
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,4660,4751,4827,4927,4927,4927,5034,5081,5167,5222
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,1994,2002,2023,2025,2025,2025,2041,2066,2093,2130
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,1315,1332,1341,1349,1349,1349,1369,1387,1408,1426

## Activity 2 - Adjust data types for countyFIPS in dataframe to make them strings.

In [6]:
df_confirmed_cases = df_confirmed_cases.astype({'countyFIPS': str})
df_confirmed_cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2022-01-18,2022-01-19,2022-01-20,2022-01-21,2022-01-22,2022-01-23,2022-01-24,2022-01-25,2022-01-26,2022-01-27
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,12738,12833,12928,13019,13019,13019,13251,13251,13251,13251
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,47143,47662,48338,49168,49168,49168,50313,50313,50313,50313
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,4741,4800,4843,4902,4902,4902,5054,5054,5054,5054
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,5385,5486,5565,5663,5663,5663,5795,5795,5795,5795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,9082,9184,9241,9449,9449,9449,9609,9712,9810,10007
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,8531,8638,8741,8814,8814,8814,8960,9049,9121,9195
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,4660,4751,4827,4927,4927,4927,5034,5081,5167,5222
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,1994,2002,2023,2025,2025,2025,2041,2066,2093,2130
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,1315,1332,1341,1349,1349,1349,1369,1387,1408,1426

## Activity 3: Upload the google mobility data and change the format for the countyFIPS

In [7]:
df_google_mobility_data = pd.read_csv(os.path.join(dir_input, 
                                                   "Google",
                                                   "Region_Mobility_Report_CSVs",
                                                   "2020_US_Region_Mobility_Report.csv"))
df_google_mobility_data

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812060,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN
812061,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-28,NaN,NaN,NaN,NaN,-40.0,NaN
812062,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-29,NaN,NaN,NaN,NaN,-43.0,NaN
812063,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-30,NaN,NaN,NaN,NaN,-40.0,NaN
812064,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,ChIJd4Rqhed3YocR7ubT5-HgoJg,2020-12-31,NaN,NaN,NaN,NaN,-38.0,NaN

Select 'sub_region_1','census_fips_code', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'

In [8]:
df_google_mobility_data_selected = df_google_mobility_data[['sub_region_1','census_fips_code', 'date',
                                                             'retail_and_recreation_percent_change_from_baseline',
                                                             'grocery_and_pharmacy_percent_change_from_baseline',
                                                             'parks_percent_change_from_baseline',
                                                             'transit_stations_percent_change_from_baseline',
                                                             'workplaces_percent_change_from_baseline',
                                                             'residential_percent_change_from_baseline']]
                                              
df_google_mobility_data_selected

,sub_region_1,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
812060,Wyoming,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN
812061,Wyoming,56045.0,2020-12-28,NaN,NaN,NaN,NaN,-40.0,NaN
812062,Wyoming,56045.0,2020-12-29,NaN,NaN,NaN,NaN,-43.0,NaN
812063,Wyoming,56045.0,2020-12-30,NaN,NaN,NaN,NaN,-40.0,NaN
812064,Wyoming,56045.0,2020-12-31,NaN,NaN,NaN,NaN,-38.0,NaN

In [9]:
df_google_mobility_data_selected = df_google_mobility_data_selected.rename(columns={"census_fips_code": "countyFIPS"})
df_google_mobility_data_selected

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
812060,Wyoming,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN
812061,Wyoming,56045.0,2020-12-28,NaN,NaN,NaN,NaN,-40.0,NaN
812062,Wyoming,56045.0,2020-12-29,NaN,NaN,NaN,NaN,-43.0,NaN
812063,Wyoming,56045.0,2020-12-30,NaN,NaN,NaN,NaN,-40.0,NaN
812064,Wyoming,56045.0,2020-12-31,NaN,NaN,NaN,NaN,-38.0,NaN

In [10]:
df_google_mobility_data_selected.columns

Index(['sub_region_1', 'countyFIPS', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'],
      dtype='object')

In [11]:
df_google_mobility_data_selected = df_google_mobility_data_selected.dropna(subset=['countyFIPS'
])

## PD3.3 Start with the DataFrame you created here. Change countyFIPS to string.

In [12]:
df_google_mobility_data_selected = df_google_mobility_data_selected.astype({'countyFIPS': int})

In [13]:
df_google_mobility_data_selected = df_google_mobility_data_selected.astype({'countyFIPS': str})

In [14]:
df_google_mobility_data_selected

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
642,Alabama,1001,2020-02-15,5.0,7.0,NaN,NaN,-4.0,NaN
643,Alabama,1001,2020-02-16,0.0,1.0,-23.0,NaN,-4.0,NaN
644,Alabama,1001,2020-02-17,8.0,0.0,NaN,NaN,-27.0,5.0
645,Alabama,1001,2020-02-18,-2.0,0.0,NaN,NaN,2.0,0.0
646,Alabama,1001,2020-02-19,-2.0,0.0,NaN,NaN,2.0,0.0
...,...,...,...,...,...,...,...,...,...
812060,Wyoming,56045,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN
812061,Wyoming,56045,2020-12-28,NaN,NaN,NaN,NaN,-40.0,NaN
812062,Wyoming,56045,2020-12-29,NaN,NaN,NaN,NaN,-43.0,NaN
812063,Wyoming,56045,2020-12-30,NaN,NaN,NaN,NaN,-40.0,NaN
812064,Wyoming,56045,2020-12-31,NaN,NaN,NaN,NaN,-38.0,NaN