In [1]:
import os
import pandas as pd
#import json
#from datetime import datetime
#from datetime import timedelta

In [2]:
using_Google_colab = False
using_Anaconda_on_Mac_or_Linux = True
using_Anaconda_on_windows = False

In [3]:
if using_Google_colab:
    from google.colab import drive
    drive.mount('/content/drive')

# DU1.1 		Open USA Facts Data Source and list data sets

In [4]:
if using_Google_colab:
  files_USA_Facts = os.listdir('/content/drive/MyDrive/COVID_Project/input/USA_Facts')
if using_Anaconda_on_Mac_or_Linux:
  files_USA_Facts = os.listdir("../input/USA_Facts")
if using_Anaconda_on_windows:
  files_USA_Facts = os.listdir(r"..\input\USA_Facts")
files_USA_Facts

['Provisional_COVID-19_Death_Counts_by_Week_Ending_Date_and_State.csv',
 'nursing_home_residents_usafacts.csv',
 'percent_of_adults_with_asthma_usafacts.csv',
 'confirmed_cases_by_state.csv',
 'children_receiving_school_lunch_usafacts.csv',
 'covid_deaths_usafacts.csv',
 'people_in_food-insecure_households_usafacts.csv',
 'covid_county_population_usafacts.csv',
 'homeless_population_usafacts.csv',
 'percent_of_adults_with_diabetes_usafacts.csv',
 'incremental_cases_by_state.csv',
 'covid_confirmed_usafacts.csv',
 'households_usafacts.csv',
 'covid_confirmed_usafacts.xlsx',
 'Archive.zip',
 'hospital_beds_usafacts.csv']

#   DU1.2		Understand number of files included in this data source

In [5]:
len(files_USA_Facts)

16

# DU1.3		Repeat the same for next data source  - Owid-covid-global

In [6]:
if using_Google_colab:
  files_OWID_COVID = os.listdir('/content/drive/MyDrive/COVID_Project/input/OWID-COVID-Global')
if using_Anaconda_on_Mac_or_Linux:
  files_OWID_COVID = os.listdir("../input/OWID-COVID-Global")
if using_Anaconda_on_windows:
  files_USA_Facts = os.listdir(r"..\input\OWID-COVID-Global")
files_OWID_COVID

['owid-covid-data.csv']

In [7]:
len(files_OWID_COVID)

1

#  DU1.4		Repeat the same for next data source  - WHO-global

In [8]:
if using_Google_colab:
  files_WHO_Global = os.listdir('/content/drive/MyDrive/COVID_Project/input/WHO-Global')
if using_Anaconda_on_Mac_or_Linux:
  files_WHO_Global = os.listdir("../input/WHO-Global")
if using_Anaconda_on_windows:
  files_WHO_Global = os.listdir(r"..\input\WHO-Global")
files_WHO_Global

['WHO-COVID-19-global-data.csv']

In [9]:
len(files_WHO_Global)

1

# DU1.5		Repeat the same for next data source  - Google

In [10]:
if using_Google_colab:
  files_Google = os.listdir('/content/drive/MyDrive/COVID_Project/input/Google')
if using_Anaconda_on_Mac_or_Linux:
  files_Google = os.listdir("../input/Google")
if using_Anaconda_on_windows:
  files_Google = os.listdir(r"..\input\Google")
files_Google

['.DS_Store',
 'Region_Mobility_Report_CSVs.zip',
 'Region_Mobility_Report_CSVs',
 '2020_US_county_Symptom_dataset',
 'locations.csv']

In [11]:
len(files_Google)

5

#   DU2.1 		Open “covid_confirmed_usafacts” dataset file from USA Facts Data Source

In [12]:
if using_Google_colab:
  df_covid_confirmed = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/USA_Facts/covid_confirmed_usafacts.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_covid_confirmed = pd.read_csv("../input/USA_Facts/covid_confirmed_usafacts.csv")
if using_Anaconda_on_windows:
  df_covid_confirmed = pd.read_csv(r"..\input\USA_Facts\covid_confirmed_usafacts.csv")
df_covid_confirmed

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,3233,3233,3233,3329,3426,3510,3570,3647,3698,3741
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,10489,10489,10489,10898,11061,11212,11364,11556,11722,11827
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1264,1264,1264,1275,1292,1296,1309,1318,1330,1336
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,1398,1398,1398,1455,1504,1520,1548,1577,1601,1613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,2376,2384,2451,2518,2544,2574,2649,2696,2702,2718
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,1868,1886,1905,1930,1940,1958,1974,1990,1992,2002
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1281,1289,1307,1327,1352,1363,1372,1399,1406,1416
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,620,629,639,644,659,662,665,690,695,699
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,428,428,428,429,436,436,438,443,443,446

# DU2.2		Review data types included in this  Data Set - “covid_confirmed_usafacts”

In [13]:
df_covid_confirmed.columns

Index(['countyFIPS', 'County Name', 'State', 'stateFIPS', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '12/11/20', '12/12/20', '12/13/20', '12/14/20', '12/15/20', '12/16/20',
       '12/17/20', '12/18/20', '12/19/20', '12/20/20'],
      dtype='object', length=338)

# DU2.3		Review data fields included in this  Data Set - “covid_confirmed_usafacts”

In [14]:
df_covid_confirmed.describe

<bound method NDFrame.describe of       countyFIPS            County Name State  stateFIPS  1/22/20  1/23/20  \
0              0  Statewide Unallocated    AL          1        0        0
1           1001         Autauga County    AL          1        0        0
2           1003         Baldwin County    AL          1        0        0
3           1005         Barbour County    AL          1        0        0
4           1007            Bibb County    AL          1        0        0
...          ...                    ...   ...        ...      ...      ...
3190       56037      Sweetwater County    WY         56        0        0
3191       56039           Teton County    WY         56        0        0
3192       56041           Uinta County    WY         56        0        0
3193       56043        Washakie County    WY         56        0        0
3194       56045          Weston County    WY         56        0        0

      1/24/20  1/25/20  1/26/20  1/27/20  ...  12/11/20  12/12/20  12/13/20  \
0           0        0        0        0  ...         0         0         0
1           0        0        0        0  ...      3233      3233      3233
2           0        0        0        0  ...     10489     10489     10489
3           0        0        0        0  ...      1264      1264      1264
4           0        0        0        0  ...      1398      1398      1398
...       ...      ...      ...      ...  ...       ...       ...       ...
3190        0        0        0        0  ...      2376      2384      2451
3191        0        0        0        0  ...      1868      1886      1905
3192        0        0        0        0  ...      1281      1289      1307
3193        0        0        0        0  ...       620       629       639
3194        0        0        0        0  ...       428       428       428

      12/14/20  12/15/20  12/16/20  12/17/20  12/18/20  12/19/20  12/20/20
0            0         0         0         0         0         0         0
1         3329      3426      3510      3570      3647      3698      3741
2        10898     11061     11212     11364     11556     11722     11827
3         1275      1292      1296      1309      1318      1330      1336
4         1455      1504      1520      1548      1577      1601      1613
...        ...       ...       ...       ...       ...       ...       ...
3190      2518      2544      2574      2649      2696      2702      2718
3191      1930      1940      1958      1974      1990      1992      2002
3192      1327      1352      1363      1372      1399      1406      1416
3193       644       659       662       665       690       695       699
3194       429       436       436       438       443       443       446

[3195 rows x 338 columns]>

#  DU2.4		Get an estimates on total record size for this dataset - “covid_confirmed_usafacts”

In [15]:
df_covid_confirmed.shape

(3195, 338)

## DU2.5 Repeat the same for other datasets  in this data sources - Let's use file "covid_deaths_usafacts.csv" file in USA_Facts - CLASS ASSIGNMENT

In [5]:
if using_Google_colab:
  df_covid_deaths = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/USA_Facts/covid_deaths_usafacts.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_covid_deaths = pd.read_csv("../input/USA_Facts/covid_deaths_usafacts.csv")
if using_Anaconda_on_windows:
  df_covid_deaths = pd.read_csv(r"..\input\USA_Facts\covid_deaths_usafacts.csv")
df_covid_deaths

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,41,41,41,41,43,43,43,44,44,44
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,141,141,141,141,141,145,145,146,147,147
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,32,32
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,39,39,39,39,39,42,42,42,42,42
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,47,47,47,47,49,50,52,52,54,54
6,1011,Bullock County,AL,1,0,0,0,0,0,0,...,20,20,20,20,20,20,20,20,20,20
7,1013,Butler County,AL,1,0,0,0,0,0,0,...,44,44,44,44,44,44,44,45,45,45
8,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,129,129,129,129,130,135,136,137,140,140
9,1017,Chambers County,AL,1,0,0,0,0,0,0,...,55,55,55,57,57,57,58,58,60,60
10,1019,Cherokee County,AL,1,0,0,0,0,0,0,...,23,23,23,23,23,23,23,23,23,23
11,1021,Chilton County,AL,1,0,0,0,0,0,0,...,46,46,46,46,46,46,47,47,49,49
12,1023,Choctaw County,AL,1,0,0,0,0,0,0,...,20,20,20,20,20,20,20,20,21,21
13,1025,Clarke County,AL,1,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24
14,1027,Clay County,AL,1,0,0,0,0,0,0,...,28,28,28,28,28,29,29,29,29,29
15,1029,Cleburne County,AL,1,0,0,0,0,0,0,...,14,14,14,15,15,15,15,15,15,15
16,1031,Coffee County,AL,1,0,0,0,0,0,0,...,25,25,25,25,25,26,29,29,31,31
17,1033,Colbert County,AL,1,0,0,0,0,0,0,...,53,53,53,53,53,53,55,56,56,56
18,1035,Conecuh County,AL,1,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,16,16
19,1037,Coosa County,AL,1,0,0,0,0,0,0,...,4,4,4,4,4,4,5,6,6,6
20,1039,Covington County,AL,1,0,0,0,0,0,0,...,38,38,38,38,38,38,38,38,38,38
21,1041,Crenshaw County,AL,1,0,0,0,0,0,0,...,32,32,32,32,32,32,32,33,33,33
22,1043,Cullman County,AL,1,0,0,0,0,0,0,...,57,57,57,59,61,64,64,67,69,69
23,1045,Dale County,AL,1,0,0,0,0,0,0,...,59,59,59,59,59,59,59,59,59,59
24,1047,Dallas County,AL,1,0,0,0,0,0,0,...,34,34,34,34,34,34,36,36,36,36
25,1049,DeKalb County,AL,1,0,0,0,0,0,0,...,48,48,48,49,49,50,51,51,51,51
26,1051,Elmore County,AL,1,0,0,0,0,0,0,...,72,72,72,72,74,76,78,78,80,80
27,1053,Escambia County,AL,1,0,0,0,0,0,0,...,32,32,32,32,32,32,33,33,33,33
28,1055,Etowah County,AL,1,0,0,0,0,0,0,...,80,80,80,80,80,80,82,82,82,82
29,1057,Fayette County,AL,1,0,0,0,0,0,0,...,16,16,16,16,16,18,18,18,18,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3165,55131,Washington County,WI,55,0,0,0,0,0,0,...,86,86,87,87,87,89,89,90,92,92
3166,55133,Waukesha County,WI,55,0,0,0,0,0,0,...,276,279,282,284,289,292,295,299,305,305
3167,55135,Waupaca County,WI,55,0,0,0,0,0,0,...,92,92,92,92,93,93,94,95,95,95
3168,55137,Waushara County,WI,55,0,0,0,0,0,0,...,13,13,13,13,13,13,13,14,14,14
3169,55139,Winnebago County,WI,55,0,0,0,0,0,0,...,137,137,137,138,138,139,144,144,144,146
3170,55141,Wood County,WI,55,0,0,0,0,0,0,...,31,31,31,31,32,33,35,35,35,35
3171,0,Statewide Unallocated,WY,56,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3172,56001,Albany County,WY,56,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
3173,56003,Big Horn County,WY,56,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,15,15
3174,56005,Campbell County,WY,56,0,0,0,0,0,0,...,20,20,20,20,22,22,22,22,22,22
3175,56007,Carbon County,WY,56,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,12
3176,56009,Converse County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,10,10,10,10
3177,56011,Crook County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
3178,56013,Fremont County,WY,56,0,0,0,0,0,0,...,51,51,51,51,52,52,54,54,54,54
3179,56015,Goshen County,WY,56,0,0,0,0,0,0,...,12,12,12,12,12,12,13,13,13,13
3180,56017,Hot Springs County,WY,56,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3181,56019,Johnson County,WY,56,0,0,0,0,0,0,...,5,5,5,5,5,5,5,5,5,5
3182,56021,Laramie County,WY,56,0,0,0,0,0,0,...,41,41,41,41,43,43,47,47,47,47
3183,56023,Lincoln County,WY,56,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,10
3184,56025,Natrona County,WY,56,0,0,0,0,0,0,...,62,62,62,62,63,63,74,74,74,74
3185,56027,Niobrara County,WY,56,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3186,56029,Park County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
3187,56031,Platte County,WY,56,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
3188,56033,Sheridan County,WY,56,0,0,0,0,0,0,...,13,13,13,13,13,13,15,15,15,15
3189,56035,Sublette County,WY,56,0,0,0,0,0,0,...,5,5,5,5,5,5,5,5,5,5
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,14,14,14,14,15,15,15,15,15,15
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,11
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2

In [6]:
df_covid_deaths.columns

Index(['countyFIPS', 'County Name', 'State', 'stateFIPS', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '12/11/20', '12/12/20', '12/13/20', '12/14/20', '12/15/20', '12/16/20',
       '12/17/20', '12/18/20', '12/19/20', '12/20/20'],
      dtype='object', length=338)

In [9]:
df_covid_deaths.describe

<bound method NDFrame.describe of       countyFIPS            County Name State  stateFIPS  1/22/20  1/23/20  \
0              0  Statewide Unallocated    AL          1        0        0
1           1001         Autauga County    AL          1        0        0
2           1003         Baldwin County    AL          1        0        0
3           1005         Barbour County    AL          1        0        0
4           1007            Bibb County    AL          1        0        0
5           1009          Blount County    AL          1        0        0
6           1011         Bullock County    AL          1        0        0
7           1013          Butler County    AL          1        0        0
8           1015         Calhoun County    AL          1        0        0
9           1017        Chambers County    AL          1        0        0
10          1019        Cherokee County    AL          1        0        0
11          1021         Chilton County    AL          1        0        0
12          1023         Choctaw County    AL          1        0        0
13          1025          Clarke County    AL          1        0        0
14          1027            Clay County    AL          1        0        0
15          1029        Cleburne County    AL          1        0        0
16          1031          Coffee County    AL          1        0        0
17          1033         Colbert County    AL          1        0        0
18          1035         Conecuh County    AL          1        0        0
19          1037           Coosa County    AL          1        0        0
20          1039       Covington County    AL          1        0        0
21          1041        Crenshaw County    AL          1        0        0
22          1043         Cullman County    AL          1        0        0
23          1045            Dale County    AL          1        0        0
24          1047          Dallas County    AL          1        0        0
25          1049          DeKalb County    AL          1        0        0
26          1051          Elmore County    AL          1        0        0
27          1053        Escambia County    AL          1        0        0
28          1055          Etowah County    AL          1        0        0
29          1057         Fayette County    AL          1        0        0
...          ...                    ...   ...        ...      ...      ...
3165       55131      Washington County    WI         55        0        0
3166       55133        Waukesha County    WI         55        0        0
3167       55135         Waupaca County    WI         55        0        0
3168       55137        Waushara County    WI         55        0        0
3169       55139       Winnebago County    WI         55        0        0
3170       55141            Wood County    WI         55        0        0
3171           0  Statewide Unallocated    WY         56        0        0
3172       56001          Albany County    WY         56        0        0
3173       56003        Big Horn County    WY         56        0        0
3174       56005        Campbell County    WY         56        0        0
3175       56007          Carbon County    WY         56        0        0
3176       56009        Converse County    WY         56        0        0
3177       56011           Crook County    WY         56        0        0
3178       56013         Fremont County    WY         56        0        0
3179       56015          Goshen County    WY         56        0        0
3180       56017     Hot Springs County    WY         56        0        0
3181       56019         Johnson County    WY         56        0        0
3182       56021         Laramie County    WY         56        0        0
3183       56023         Lincoln County    WY         56        0        0
3184       56025         Natrona County    WY         56        0        0
3185       56027        Niobrara County    WY         56        0        0
3186       56029            Park County    WY         56        0        0
3187       56031          Platte County    WY         56        0        0
3188       56033        Sheridan County    WY         56        0        0
3189       56035        Sublette County    WY         56        0        0
3190       56037      Sweetwater County    WY         56        0        0
3191       56039           Teton County    WY         56        0        0
3192       56041           Uinta County    WY         56        0        0
3193       56043        Washakie County    WY         56        0        0
3194       56045          Weston County    WY         56        0        0

      1/24/20  1/25/20  1/26/20  1/27/20    ...     12/11/20  12/12/20  \
0           0        0        0        0    ...            0         0
1           0        0        0        0    ...           41        41
2           0        0        0        0    ...          141       141
3           0        0        0        0    ...           30        30
4           0        0        0        0    ...           39        39
5           0        0        0        0    ...           47        47
6           0        0        0        0    ...           20        20
7           0        0        0        0    ...           44        44
8           0        0        0        0    ...          129       129
9           0        0        0        0    ...           55        55
10          0        0        0        0    ...           23        23
11          0        0        0        0    ...           46        46
12          0        0        0        0    ...           20        20
13          0        0        0        0    ...           24        24
14          0        0        0        0    ...           28        28
15          0        0        0        0    ...           14        14
16          0        0        0        0    ...           25        25
17          0        0        0        0    ...           53        53
18          0        0        0        0    ...           15        15
19          0        0        0        0    ...            4         4
20          0        0        0        0    ...           38        38
21          0        0        0        0    ...           32        32
22          0        0        0        0    ...           57        57
23          0        0        0        0    ...           59        59
24          0        0        0        0    ...           34        34
25          0        0        0        0    ...           48        48
26          0        0        0        0    ...           72        72
27          0        0        0        0    ...           32        32
28          0        0        0        0    ...           80        80
29          0        0        0        0    ...           16        16
...       ...      ...      ...      ...    ...          ...       ...
3165        0        0        0        0    ...           86        86
3166        0        0        0        0    ...          276       279
3167        0        0        0        0    ...           92        92
3168        0        0        0        0    ...           13        13
3169        0        0        0        0    ...          137       137
3170        0        0        0        0    ...           31        31
3171        0        0        0        0    ...            0         0
3172        0        0        0        0    ...            9         9
3173        0        0        0        0    ...           15        15
3174        0        0        0        0    ...           20        20
3175        0        0        0        0    ...           12        12
3176        0        0        0        0    ...            7         7
3177        0        0        0        0    ...            6         6
3178        0        0        0        0    ...           51        51
3179        0        0        0        0    ...           12        12
3180        0        0        0        0    ...            1         1
3181        0        0        0        0    ...            5         5
3182        0        0        0        0    ...           41        41
3183        0        0        0        0    ...           10        10
3184        0        0        0        0    ...           62        62
3185        0        0        0        0    ...            1         1
3186        0        0        0        0    ...            7         7
3187        0        0        0        0    ...            8         8
3188        0        0        0        0    ...           13        13
3189        0        0        0        0    ...            5         5
3190        0        0        0        0    ...           14        14
3191        0        0        0        0    ...            2         2
3192        0        0        0        0    ...            7         7
3193        0        0        0        0    ...           11        11
3194        0        0        0        0    ...            2         2

      12/13/20  12/14/20  12/15/20  12/16/20  12/17/20  12/18/20  12/19/20  \
0            0         0         0         0         0         0         0
1           41        41        43        43        43        44        44
2          141       141       141       145       145       146       147
3           30        30        30        30        30        30        32
4           39        39        39        42        42        42        42
5           47        47        49        50        52        52        54
6           20        20        20        20        20        20        20
7           44        44        44        44        44        45        45
8          129       129       130       135       136       137       140
9           55        57        57        57        58        58        60
10          23        23        23        23        23        23        23
11          46        46        46        46        47        47        49
12          20        20        20        20        20        20        21
13          24        24        24        24        24        24        24
14          28        28        28        29        29        29        29
15          14        15        15        15        15        15        15
16          25        25        25        26        29        29        31
17          53        53        53        53        55        56        56
18          15        15        15        15        15        15        16
19           4         4         4         4         5         6         6
20          38        38        38        38        38        38        38
21          32        32        32        32        32        33        33
22          57        59        61        64        64        67        69
23          59        59        59        59        59        59        59
24          34        34        34        34        36        36        36
25          48        49        49        50        51        51        51
26          72        72        74        76        78        78        80
27          32        32        32        32        33        33        33
28          80        80        80        80        82        82        82
29          16        16        16        18        18        18        18
...        ...       ...       ...       ...       ...       ...       ...
3165        87        87        87        89        89        90        92
3166       282       284       289       292       295       299       305
3167        92        92        93        93        94        95        95
3168        13        13        13        13        13        14        14
3169       137       138       138       139       144       144       144
3170        31        31        32        33        35        35        35
3171         0         0         0         0         0         0         0
3172         9         9         9         9         9         9         9
3173        15        15        15        15        15        15        15
3174        20        20        22        22        22        22        22
3175        12        12        12        12        12        12        12
3176         7         7         7         7        10        10        10
3177         6         6         6         6         6         6         6
3178        51        51        52        52        54        54        54
3179        12        12        12        12        13        13        13
3180         1         1         1         1         1         1         1
3181         5         5         5         5         5         5         5
3182        41        41        43        43        47        47        47
3183        10        10        10        10        10        10        10
3184        62        62        63        63        74        74        74
3185         1         1         1         1         1         1         1
3186         7         7         7         7         7         7         7
3187         8         8         8         8         8         8         8
3188        13        13        13        13        15        15        15
3189         5         5         5         5         5         5         5
3190        14        14        15        15        15        15        15
3191         2         2         2         2         2         2         2
3192         7         7         7         7         7         7         7
3193        11        11        11        11        11        11        11
3194         2         2         2         2         2         2         2

      12/20/20
0            0
1           44
2          147
3           32
4           42
5           54
6           20
7           45
8          140
9           60
10          23
11          49
12          21
13          24
14          29
15          15
16          31
17          56
18          16
19           6
20          38
21          33
22          69
23          59
24          36
25          51
26          80
27          33
28          82
29          18
...        ...
3165        92
3166       305
3167        95
3168        14
3169       146
3170        35
3171         0
3172         9
3173        15
3174        22
3175        12
3176        10
3177         6
3178        54
3179        13
3180         1
3181         5
3182        47
3183        10
3184        74
3185         1
3186         7
3187         8
3188        15
3189         5
3190        15
3191         2
3192         7
3193        11
3194         2

[3195 rows x 338 columns]>

## DU2.6 If desired, above process can be repeated for other  data sources - Owid-covid-global - CLASS ASSIGMENT

In [10]:
if using_Google_colab:
  df_owid_covid_global = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/OWID-COVID-Global/owid-covid-data.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_owid_covid_global = pd.read_csv("../input/OWID-COVID-Global/owid-covid-data.csv")
if using_Anaconda_on_windows:
  df_owid_covid_global = pd.read_csv(r"..\input\OWID-COVID-Global/owid-covid-data.csv")
df_owid_covid_global

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,Death / per capita,new_deaths,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,12/31/19,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
1,AFG,Asia,Afghanistan,1/1/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
2,AFG,Asia,Afghanistan,1/2/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
3,AFG,Asia,Afghanistan,1/3/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
4,AFG,Asia,Afghanistan,1/4/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
5,AFG,Asia,Afghanistan,1/5/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
6,AFG,Asia,Afghanistan,1/6/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
7,AFG,Asia,Afghanistan,1/7/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
8,AFG,Asia,Afghanistan,1/8/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
9,AFG,Asia,Afghanistan,1/9/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
10,AFG,Asia,Afghanistan,1/10/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
11,AFG,Asia,Afghanistan,1/11/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
12,AFG,Asia,Afghanistan,1/12/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
13,AFG,Asia,Afghanistan,1/13/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
14,AFG,Asia,Afghanistan,1/14/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
15,AFG,Asia,Afghanistan,1/15/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
16,AFG,Asia,Afghanistan,1/16/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
17,AFG,Asia,Afghanistan,1/17/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
18,AFG,Asia,Afghanistan,1/18/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
19,AFG,Asia,Afghanistan,1/19/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
20,AFG,Asia,Afghanistan,1/20/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
21,AFG,Asia,Afghanistan,1/21/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
22,AFG,Asia,Afghanistan,1/22/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
23,AFG,Asia,Afghanistan,1/23/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
24,AFG,Asia,Afghanistan,1/24/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
25,AFG,Asia,Afghanistan,1/25/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
26,AFG,Asia,Afghanistan,1/26/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
27,AFG,Asia,Afghanistan,1/27/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
28,AFG,Asia,Afghanistan,1/28/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
29,AFG,Asia,Afghanistan,1/29/20,NaN,0.0,0.0,NaN,NaN,0.0,...,597.029,9.59,NaN,NaN,37.746,0.5,64.830,0.498,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53927,NaN,NaN,International,10/3/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53928,NaN,NaN,International,10/4/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53929,NaN,NaN,International,10/5/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53930,NaN,NaN,International,10/6/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53931,NaN,NaN,International,10/7/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53932,NaN,NaN,International,10/8/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53933,NaN,NaN,International,10/9/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53934,NaN,NaN,International,10/10/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53935,NaN,NaN,International,10/11/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53936,NaN,NaN,International,10/12/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53937,NaN,NaN,International,10/13/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53938,NaN,NaN,International,10/14/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53939,NaN,NaN,International,10/15/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53940,NaN,NaN,International,10/16/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53941,NaN,NaN,International,10/17/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53942,NaN,NaN,International,10/18/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53943,NaN,NaN,International,10/19/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53944,NaN,NaN,International,10/20/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53945,NaN,NaN,International,10/21/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53946,NaN,NaN,International,10/22/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53947,NaN,NaN,International,10/23/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53948,NaN,NaN,International,10/24/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53949,NaN,NaN,International,10/25/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53950,NaN,NaN,International,10/26/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53951,NaN,NaN,International,10/27/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53952,NaN,NaN,International,10/28/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53953,NaN,NaN,International,10/29/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53954,NaN,NaN,International,10/30/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53955,NaN,NaN,International,10/31/20,696.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53956,NaN,NaN,International,11/1/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_owid_covid_global.describe

<bound method NDFrame.describe of       iso_code continent       location      date  total_cases  new_cases  \
0          AFG      Asia    Afghanistan  12/31/19          NaN        0.0
1          AFG      Asia    Afghanistan    1/1/20          NaN        0.0
2          AFG      Asia    Afghanistan    1/2/20          NaN        0.0
3          AFG      Asia    Afghanistan    1/3/20          NaN        0.0
4          AFG      Asia    Afghanistan    1/4/20          NaN        0.0
5          AFG      Asia    Afghanistan    1/5/20          NaN        0.0
6          AFG      Asia    Afghanistan    1/6/20          NaN        0.0
7          AFG      Asia    Afghanistan    1/7/20          NaN        0.0
8          AFG      Asia    Afghanistan    1/8/20          NaN        0.0
9          AFG      Asia    Afghanistan    1/9/20          NaN        0.0
10         AFG      Asia    Afghanistan   1/10/20          NaN        0.0
11         AFG      Asia    Afghanistan   1/11/20          NaN        0.0
12         AFG      Asia    Afghanistan   1/12/20          NaN        0.0
13         AFG      Asia    Afghanistan   1/13/20          NaN        0.0
14         AFG      Asia    Afghanistan   1/14/20          NaN        0.0
15         AFG      Asia    Afghanistan   1/15/20          NaN        0.0
16         AFG      Asia    Afghanistan   1/16/20          NaN        0.0
17         AFG      Asia    Afghanistan   1/17/20          NaN        0.0
18         AFG      Asia    Afghanistan   1/18/20          NaN        0.0
19         AFG      Asia    Afghanistan   1/19/20          NaN        0.0
20         AFG      Asia    Afghanistan   1/20/20          NaN        0.0
21         AFG      Asia    Afghanistan   1/21/20          NaN        0.0
22         AFG      Asia    Afghanistan   1/22/20          NaN        0.0
23         AFG      Asia    Afghanistan   1/23/20          NaN        0.0
24         AFG      Asia    Afghanistan   1/24/20          NaN        0.0
25         AFG      Asia    Afghanistan   1/25/20          NaN        0.0
26         AFG      Asia    Afghanistan   1/26/20          NaN        0.0
27         AFG      Asia    Afghanistan   1/27/20          NaN        0.0
28         AFG      Asia    Afghanistan   1/28/20          NaN        0.0
29         AFG      Asia    Afghanistan   1/29/20          NaN        0.0
...        ...       ...            ...       ...          ...        ...
53927      NaN       NaN  International   10/3/20        696.0        NaN
53928      NaN       NaN  International   10/4/20        696.0        NaN
53929      NaN       NaN  International   10/5/20        696.0        NaN
53930      NaN       NaN  International   10/6/20        696.0        NaN
53931      NaN       NaN  International   10/7/20        696.0        NaN
53932      NaN       NaN  International   10/8/20        696.0        NaN
53933      NaN       NaN  International   10/9/20        696.0        NaN
53934      NaN       NaN  International  10/10/20        696.0        NaN
53935      NaN       NaN  International  10/11/20        696.0        NaN
53936      NaN       NaN  International  10/12/20        696.0        NaN
53937      NaN       NaN  International  10/13/20        696.0        NaN
53938      NaN       NaN  International  10/14/20        696.0        NaN
53939      NaN       NaN  International  10/15/20        696.0        NaN
53940      NaN       NaN  International  10/16/20        696.0        NaN
53941      NaN       NaN  International  10/17/20        696.0        NaN
53942      NaN       NaN  International  10/18/20        696.0        NaN
53943      NaN       NaN  International  10/19/20        696.0        NaN
53944      NaN       NaN  International  10/20/20        696.0        NaN
53945      NaN       NaN  International  10/21/20        696.0        NaN
53946      NaN       NaN  International  10/22/20        696.0        NaN
53947      NaN       NaN  International  10/23/20        696.0        NaN
53948      NaN       NaN  International  10/24/20        696.0        NaN
53949      NaN       NaN  International  10/25/20        696.0        NaN
53950      NaN       NaN  International  10/26/20        696.0        NaN
53951      NaN       NaN  International  10/27/20        696.0        NaN
53952      NaN       NaN  International  10/28/20        696.0        NaN
53953      NaN       NaN  International  10/29/20        696.0        NaN
53954      NaN       NaN  International  10/30/20        696.0        NaN
53955      NaN       NaN  International  10/31/20        696.0        NaN
53956      NaN       NaN  International   11/1/20        696.0        NaN

       new_cases_smoothed  total_deaths  Death / per capita  new_deaths  \
0                     NaN           NaN                 NaN         0.0
1                     NaN           NaN                 NaN         0.0
2                     NaN           NaN                 NaN         0.0
3                     NaN           NaN                 NaN         0.0
4                     NaN           NaN                 NaN         0.0
5                     NaN           NaN                 NaN         0.0
6                     0.0           NaN                 NaN         0.0
7                     0.0           NaN                 NaN         0.0
8                     0.0           NaN                 NaN         0.0
9                     0.0           NaN                 NaN         0.0
10                    0.0           NaN                 NaN         0.0
11                    0.0           NaN                 NaN         0.0
12                    0.0           NaN                 NaN         0.0
13                    0.0           NaN                 NaN         0.0
14                    0.0           NaN                 NaN         0.0
15                    0.0           NaN                 NaN         0.0
16                    0.0           NaN                 NaN         0.0
17                    0.0           NaN                 NaN         0.0
18                    0.0           NaN                 NaN         0.0
19                    0.0           NaN                 NaN         0.0
20                    0.0           NaN                 NaN         0.0
21                    0.0           NaN                 NaN         0.0
22                    0.0           NaN                 NaN         0.0
23                    0.0           NaN                 NaN         0.0
24                    0.0           NaN                 NaN         0.0
25                    0.0           NaN                 NaN         0.0
26                    0.0           NaN                 NaN         0.0
27                    0.0           NaN                 NaN         0.0
28                    0.0           NaN                 NaN         0.0
29                    0.0           NaN                 NaN         0.0
...                   ...           ...                 ...         ...
53927                 NaN           7.0                 NaN         NaN
53928                 NaN           7.0                 NaN         NaN
53929                 NaN           7.0                 NaN         NaN
53930                 NaN           7.0                 NaN         NaN
53931                 NaN           7.0                 NaN         NaN
53932                 NaN           7.0                 NaN         NaN
53933                 NaN           7.0                 NaN         NaN
53934                 NaN           7.0                 NaN         NaN
53935                 NaN           7.0                 NaN         NaN
53936                 NaN           7.0                 NaN         NaN
53937                 NaN           7.0                 NaN         NaN
53938                 NaN           7.0                 NaN         NaN
53939                 NaN           7.0                 NaN         NaN
53940                 NaN           7.0                 NaN         NaN
53941                 NaN           7.0                 NaN         NaN
53942                 NaN           7.0                 NaN         NaN
53943                 NaN           7.0                 NaN         NaN
53944                 NaN           7.0                 NaN         NaN
53945                 NaN           7.0                 NaN         NaN
53946                 NaN           7.0                 NaN         NaN
53947                 NaN           7.0                 NaN         NaN
53948                 NaN           7.0                 NaN         NaN
53949                 NaN           7.0                 NaN         NaN
53950                 NaN           7.0                 NaN         NaN
53951                 NaN           7.0                 NaN         NaN
53952                 NaN           7.0                 NaN         NaN
53953                 NaN           7.0                 NaN         NaN
53954                 NaN           7.0                 NaN         NaN
53955                 NaN           NaN                 NaN         NaN
53956                 NaN           7.0                 NaN         NaN

                ...             gdp_per_capita  extreme_poverty  \
0               ...                   1803.987              NaN
1               ...                   1803.987              NaN
2               ...                   1803.987              NaN
3               ...                   1803.987              NaN
4               ...                   1803.987              NaN
5               ...                   1803.987              NaN
6               ...                    597.029             9.59
7               ...                    597.029             9.59
8               ...                    597.029             9.59
9               ...                    597.029             9.59
10              ...                    597.029             9.59
11              ...                    597.029             9.59
12              ...                    597.029             9.59
13              ...                    597.029             9.59
14              ...                    597.029             9.59
15              ...                    597.029             9.59
16              ...                    597.029             9.59
17              ...                    597.029             9.59
18              ...                    597.029             9.59
19              ...                    597.029             9.59
20              ...                    597.029             9.59
21              ...                    597.029             9.59
22              ...                    597.029             9.59
23              ...                    597.029             9.59
24              ...                    597.029             9.59
25              ...                    597.029             9.59
26              ...                    597.029             9.59
27              ...                    597.029             9.59
28              ...                    597.029             9.59
29              ...                    597.029             9.59
...             ...                        ...              ...
53927           ...                        NaN              NaN
53928           ...                        NaN              NaN
53929           ...                        NaN              NaN
53930           ...                        NaN              NaN
53931           ...                        NaN              NaN
53932           ...                        NaN              NaN
53933           ...                        NaN              NaN
53934           ...                        NaN              NaN
53935           ...                        NaN              NaN
53936           ...                        NaN              NaN
53937           ...                        NaN              NaN
53938           ...                        NaN              NaN
53939           ...                        NaN              NaN
53940           ...                        NaN              NaN
53941           ...                        NaN              NaN
53942           ...                        NaN              NaN
53943           ...                        NaN              NaN
53944           ...                        NaN              NaN
53945           ...                        NaN              NaN
53946           ...                        NaN              NaN
53947           ...                        NaN              NaN
53948           ...                        NaN              NaN
53949           ...                        NaN              NaN
53950           ...                        NaN              NaN
53951           ...                        NaN              NaN
53952           ...                        NaN              NaN
53953           ...                        NaN              NaN
53954           ...                        NaN              NaN
53955           ...                        NaN              NaN
53956           ...                        NaN              NaN

       cardiovasc_death_rate  diabetes_prevalence  female_smokers  \
0                    597.029                 9.59             NaN
1                    597.029                 9.59             NaN
2                    597.029                 9.59             NaN
3                    597.029                 9.59             NaN
4                    597.029                 9.59             NaN
5                    597.029                 9.59             NaN
6                        NaN                  NaN          37.746
7                        NaN                  NaN          37.746
8                        NaN                  NaN          37.746
9                        NaN                  NaN          37.746
10                       NaN                  NaN          37.746
11                       NaN                  NaN          37.746
12                       NaN                  NaN          37.746
13                       NaN                  NaN          37.746
14                       NaN                  NaN          37.746
15                       NaN                  NaN          37.746
16                       NaN                  NaN          37.746
17                       NaN                  NaN          37.746
18                       NaN                  NaN          37.746
19                       NaN                  NaN          37.746
20                       NaN                  NaN          37.746
21                       NaN                  NaN          37.746
22                       NaN                  NaN          37.746
23                       NaN                  NaN          37.746
24                       NaN                  NaN          37.746
25                       NaN                  NaN          37.746
26                       NaN                  NaN          37.746
27                       NaN                  NaN          37.746
28                       NaN                  NaN          37.746
29                       NaN                  NaN          37.746
...                      ...                  ...             ...
53927                    NaN                  NaN             NaN
53928                    NaN                  NaN             NaN
53929                    NaN                  NaN             NaN
53930                    NaN                  NaN             NaN
53931                    NaN                  NaN             NaN
53932                    NaN                  NaN             NaN
53933                    NaN                  NaN             NaN
53934                    NaN                  NaN             NaN
53935                    NaN                  NaN             NaN
53936                    NaN                  NaN             NaN
53937                    NaN                  NaN             NaN
53938                    NaN                  NaN             NaN
53939                    NaN                  NaN             NaN
53940                    NaN                  NaN             NaN
53941                    NaN                  NaN             NaN
53942                    NaN                  NaN             NaN
53943                    NaN                  NaN             NaN
53944                    NaN                  NaN             NaN
53945                    NaN                  NaN             NaN
53946                    NaN                  NaN             NaN
53947                    NaN                  NaN             NaN
53948                    NaN                  NaN             NaN
53949                    NaN                  NaN             NaN
53950                    NaN                  NaN             NaN
53951                    NaN                  NaN             NaN
53952                    NaN                  NaN             NaN
53953                    NaN                  NaN             NaN
53954                    NaN                  NaN             NaN
53955                    NaN                  NaN             NaN
53956                    NaN                  NaN             NaN

       male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0               NaN                  37.746                       0.500
1               NaN                  37.746                       0.500
2               NaN                  37.746                       0.500
3               NaN                  37.746                       0.500
4               NaN                  37.746                       0.500
5               NaN                  37.746                       0.500
6               0.5                  64.830                       0.498
7               0.5                  64.830                       0.498
8               0.5                  64.830                       0.498
9               0.5                  64.830                       0.498
10              0.5                  64.830                       0.498
11              0.5                  64.830                       0.498
12              0.5                  64.830                       0.498
13              0.5                  64.830                       0.498
14              0.5                  64.830                       0.498
15              0.5                  64.830                       0.498
16              0.5                  64.830                       0.498
17              0.5                  64.830                       0.498
18              0.5                  64.830                       0.498
19              0.5                  64.830                       0.498
20              0.5                  64.830                       0.498
21              0.5                  64.830                       0.498
22              0.5                  64.830                       0.498
23              0.5                  64.830                       0.498
24              0.5                  64.830                       0.498
25              0.5                  64.830                       0.498
26              0.5                  64.830                       0.498
27              0.5                  64.830                       0.498
28              0.5                  64.830                       0.498
29              0.5                  64.830                       0.498
...             ...                     ...                         ...
53927           NaN                     NaN                         NaN
53928           NaN                     NaN                         NaN
53929           NaN                     NaN                         NaN
53930           NaN                     NaN                         NaN
53931           NaN                     NaN                         NaN
53932           NaN                     NaN                         NaN
53933           NaN                     NaN                         NaN

# DU3.1 		Classify data contents included in “covid_confirmed_usafacts” dataset file from USA Facts

In [16]:
df_covid_confirmed

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,3233,3233,3233,3329,3426,3510,3570,3647,3698,3741
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,10489,10489,10489,10898,11061,11212,11364,11556,11722,11827
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1264,1264,1264,1275,1292,1296,1309,1318,1330,1336
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,1398,1398,1398,1455,1504,1520,1548,1577,1601,1613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,2376,2384,2451,2518,2544,2574,2649,2696,2702,2718
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,1868,1886,1905,1930,1940,1958,1974,1990,1992,2002
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1281,1289,1307,1327,1352,1363,1372,1399,1406,1416
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,620,629,639,644,659,662,665,690,695,699
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,428,428,428,429,436,436,438,443,443,446

## DU3.2 Repeat the same for other datasets in this data sources (USA Facts) - covid_deaths_usafacts.csv - CLASS ASSIGNMENT

In [4]:
if using_Google_colab:
  df_covid_deaths = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/USA_Facts/covid_deaths_usafacts.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_covid_deaths = pd.read_csv("../input/USA_Facts/covid_deaths_usafacts.csv")
if using_Anaconda_on_windows:
  df_covid_deaths = pd.read_csv(r"..\input\USA_Facts\covid_deaths_usafacts.csv")
df_covid_deaths

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,41,41,41,41,43,43,43,44,44,44
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,141,141,141,141,141,145,145,146,147,147
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,32,32
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,39,39,39,39,39,42,42,42,42,42
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,47,47,47,47,49,50,52,52,54,54
6,1011,Bullock County,AL,1,0,0,0,0,0,0,...,20,20,20,20,20,20,20,20,20,20
7,1013,Butler County,AL,1,0,0,0,0,0,0,...,44,44,44,44,44,44,44,45,45,45
8,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,129,129,129,129,130,135,136,137,140,140
9,1017,Chambers County,AL,1,0,0,0,0,0,0,...,55,55,55,57,57,57,58,58,60,60
10,1019,Cherokee County,AL,1,0,0,0,0,0,0,...,23,23,23,23,23,23,23,23,23,23
11,1021,Chilton County,AL,1,0,0,0,0,0,0,...,46,46,46,46,46,46,47,47,49,49
12,1023,Choctaw County,AL,1,0,0,0,0,0,0,...,20,20,20,20,20,20,20,20,21,21
13,1025,Clarke County,AL,1,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24
14,1027,Clay County,AL,1,0,0,0,0,0,0,...,28,28,28,28,28,29,29,29,29,29
15,1029,Cleburne County,AL,1,0,0,0,0,0,0,...,14,14,14,15,15,15,15,15,15,15
16,1031,Coffee County,AL,1,0,0,0,0,0,0,...,25,25,25,25,25,26,29,29,31,31
17,1033,Colbert County,AL,1,0,0,0,0,0,0,...,53,53,53,53,53,53,55,56,56,56
18,1035,Conecuh County,AL,1,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,16,16
19,1037,Coosa County,AL,1,0,0,0,0,0,0,...,4,4,4,4,4,4,5,6,6,6
20,1039,Covington County,AL,1,0,0,0,0,0,0,...,38,38,38,38,38,38,38,38,38,38
21,1041,Crenshaw County,AL,1,0,0,0,0,0,0,...,32,32,32,32,32,32,32,33,33,33
22,1043,Cullman County,AL,1,0,0,0,0,0,0,...,57,57,57,59,61,64,64,67,69,69
23,1045,Dale County,AL,1,0,0,0,0,0,0,...,59,59,59,59,59,59,59,59,59,59
24,1047,Dallas County,AL,1,0,0,0,0,0,0,...,34,34,34,34,34,34,36,36,36,36
25,1049,DeKalb County,AL,1,0,0,0,0,0,0,...,48,48,48,49,49,50,51,51,51,51
26,1051,Elmore County,AL,1,0,0,0,0,0,0,...,72,72,72,72,74,76,78,78,80,80
27,1053,Escambia County,AL,1,0,0,0,0,0,0,...,32,32,32,32,32,32,33,33,33,33
28,1055,Etowah County,AL,1,0,0,0,0,0,0,...,80,80,80,80,80,80,82,82,82,82
29,1057,Fayette County,AL,1,0,0,0,0,0,0,...,16,16,16,16,16,18,18,18,18,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3165,55131,Washington County,WI,55,0,0,0,0,0,0,...,86,86,87,87,87,89,89,90,92,92
3166,55133,Waukesha County,WI,55,0,0,0,0,0,0,...,276,279,282,284,289,292,295,299,305,305
3167,55135,Waupaca County,WI,55,0,0,0,0,0,0,...,92,92,92,92,93,93,94,95,95,95
3168,55137,Waushara County,WI,55,0,0,0,0,0,0,...,13,13,13,13,13,13,13,14,14,14
3169,55139,Winnebago County,WI,55,0,0,0,0,0,0,...,137,137,137,138,138,139,144,144,144,146
3170,55141,Wood County,WI,55,0,0,0,0,0,0,...,31,31,31,31,32,33,35,35,35,35
3171,0,Statewide Unallocated,WY,56,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3172,56001,Albany County,WY,56,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
3173,56003,Big Horn County,WY,56,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,15,15
3174,56005,Campbell County,WY,56,0,0,0,0,0,0,...,20,20,20,20,22,22,22,22,22,22
3175,56007,Carbon County,WY,56,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,12
3176,56009,Converse County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,10,10,10,10
3177,56011,Crook County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
3178,56013,Fremont County,WY,56,0,0,0,0,0,0,...,51,51,51,51,52,52,54,54,54,54
3179,56015,Goshen County,WY,56,0,0,0,0,0,0,...,12,12,12,12,12,12,13,13,13,13
3180,56017,Hot Springs County,WY,56,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3181,56019,Johnson County,WY,56,0,0,0,0,0,0,...,5,5,5,5,5,5,5,5,5,5
3182,56021,Laramie County,WY,56,0,0,0,0,0,0,...,41,41,41,41,43,43,47,47,47,47
3183,56023,Lincoln County,WY,56,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,10
3184,56025,Natrona County,WY,56,0,0,0,0,0,0,...,62,62,62,62,63,63,74,74,74,74
3185,56027,Niobrara County,WY,56,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3186,56029,Park County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
3187,56031,Platte County,WY,56,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
3188,56033,Sheridan County,WY,56,0,0,0,0,0,0,...,13,13,13,13,13,13,15,15,15,15
3189,56035,Sublette County,WY,56,0,0,0,0,0,0,...,5,5,5,5,5,5,5,5,5,5
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,14,14,14,14,15,15,15,15,15,15
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,11
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2

## DU3.2 Repeat the same for other datasets OWID-COVID-Global - CLASS ASSIGNMENT

In [ ]:
if using_Google_colab:
  df_owid_covid_global = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/OWID-COVID-Global/owid-covid-data.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_owid_covid_global = pd.read_csv("../input/OWID-COVID-Global/owid-covid-data.csv")
if using_Anaconda_on_windows:
  df_owid_covid_global = pd.read_csv(r"..\input\OWID-COVID-Global/owid-covid-data.csv")
df_owid_covid_global

# DU4.1 		Determine basic statistics on “covid_confirmed_usafacts” dataset file from USA Facts Data Source

In [17]:
df_covid_confirmed.describe()

,countyFIPS,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
count,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,...,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000
mean,29882.221283,30.250391,0.000313,0.000313,0.000626,0.000626,0.001565,0.001878,0.001878,0.002191,...,4891.251956,4955.670110,5009.165884,5073.570579,5134.007199,5205.183725,5279.998435,5352.922066,5410.740532,5462.620657
std,15524.478700,15.159987,0.017691,0.017691,0.025016,0.025016,0.039535,0.043301,0.043301,0.053038,...,16704.131313,16962.015992,17198.318097,17436.785224,17663.260812,18021.787342,18340.382531,18664.485938,18923.501290,19154.137973
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18098.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,502.000000,510.000000,514.000000,520.500000,526.500000,534.000000,540.000000,547.000000,556.000000,561.500000
50%,29123.000000,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1264.000000,1281.000000,1290.000000,1304.000000,1322.000000,1337.000000,1352.000000,1366.000000,1376.000000,1389.000000
75%,45054.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3276.000000,3317.000000,3364.500000,3398.000000,3449.000000,3502.000000,3556.000000,3619.000000,3668.000000,3706.000000
max,56045.000000,56.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,501635.000000,512872.000000,525486.000000,532730.000000,543769.000000,566005.000000,580325.000000,596721.000000,610372.000000,623670.000000

# DU5.1 Open “covid_confirmed_usafacts” dataset file from USA Facts Data Source and determine number of missing value

In [18]:
df_covid_confirmed

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,3233,3233,3233,3329,3426,3510,3570,3647,3698,3741
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,10489,10489,10489,10898,11061,11212,11364,11556,11722,11827
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1264,1264,1264,1275,1292,1296,1309,1318,1330,1336
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,1398,1398,1398,1455,1504,1520,1548,1577,1601,1613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,2376,2384,2451,2518,2544,2574,2649,2696,2702,2718
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,1868,1886,1905,1930,1940,1958,1974,1990,1992,2002
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1281,1289,1307,1327,1352,1363,1372,1399,1406,1416
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,620,629,639,644,659,662,665,690,695,699
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,428,428,428,429,436,436,438,443,443,446

# DU5.1 Open “covid_confirmed_usafacts” dataset file from USA Facts Data Source and determine Total number of records and number of records with no value

In [19]:
statevars = ['countyFIPS', 'County Name', 'State', 'stateFIPS']

In [20]:
df_covid_confirmed[statevars].isnull().sum(axis=0)

countyFIPS     0
County Name    0
State          0
stateFIPS      0
dtype: int64

# DU5.2	 Verify data quality issues for OWID-COVID-Global data source

In [21]:
if using_Google_colab:
  df_OWID_COVID_Global = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/OWID-COVID-Global/owid-covid-data.csv')
if using_Anaconda_on_Mac_or_Linux:
  df_OWID_COVID_Global = pd.read_csv("../input/OWID-COVID-Global/owid-covid-data.csv")
if using_Anaconda_on_windows:
  df_OWID_COVID_Global = pd.read_csv(r"..\input\OWID-COVID-Global\owid-covid-data.csv")
df_OWID_COVID_Global

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,Death / per capita,new_deaths,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,12/31/19,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,1/1/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,1/2/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,1/3/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,1/4/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53952,NaN,NaN,International,10/28/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53953,NaN,NaN,International,10/29/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53954,NaN,NaN,International,10/30/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53955,NaN,NaN,International,10/31/20,696.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53956,NaN,NaN,International,11/1/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_OWID_COVID_Global.shape

(53957, 54)

In [23]:
df_OWID_COVID_Global.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'Death / per capita',
       'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'Total deaths per million', 'Unnamed: 37', 'population.1',
       'population_density', 'median_age', 'aged_65_older', 'over 65/pop',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index'],
      dtype='object')

In [24]:
df_OWID_COVID_Global

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,Death / per capita,new_deaths,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,12/31/19,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,1/1/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,1/2/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,1/3/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,1/4/20,NaN,0.0,NaN,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53952,NaN,NaN,International,10/28/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53953,NaN,NaN,International,10/29/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53954,NaN,NaN,International,10/30/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53955,NaN,NaN,International,10/31/20,696.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53956,NaN,NaN,International,11/1/20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_OWID_COVID_Global.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,Death / per capita,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,5.033000e+04,53045.000000,52247.00000,4.128300e+04,210.000000,53045.000000,52247.000000,50059.000000,52981.000000,52182.000000,...,48006.000000,49742.000000,37420.000000,36939.000000,22659.000000,43266.000000,52963.000000,46338.000000,6.00,6.000000e+00
mean,1.469059e+05,1740.178773,1708.91144,6.362527e+03,145.493394,45.100820,44.996832,2711.687481,33.331941,32.232246,...,252.355237,8.059046,10.858774,32.638493,52.204766,3.095772,73.961202,0.723029,64.83,4.980000e-01
std,1.473997e+06,15873.433805,15427.51208,5.148749e+04,217.322155,374.785516,363.423138,5339.036334,117.973160,83.805638,...,118.630243,4.164973,12.837141,13.447348,31.638059,2.517421,7.400799,0.153153,0.00,6.080942e-17
min,1.000000e+00,-8261.000000,-552.00000,1.000000e+00,0.000000,-1918.000000,-232.143000,0.001000,-2212.545000,-269.978000,...,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,37.746000,0.354000,64.83,4.980000e-01
25%,1.530000e+02,0.000000,0.71400,1.100000e+01,7.909738,0.000000,0.000000,79.953000,0.000000,0.224000,...,155.898000,5.310000,1.900000,21.400000,21.222000,1.300000,69.870000,0.601000,64.83,4.980000e-01
50%,1.847000e+03,13.000000,18.00000,7.700000e+01,51.202237,0.000000,0.286000,521.222000,2.004000,3.622500,...,238.339000,7.110000,6.400000,31.400000,52.232000,2.500000,75.400000,0.753000,64.83,4.980000e-01
75%,1.875500e+04,209.000000,217.57100,6.470000e+02,185.892581,3.000000,3.714000,3032.130500,23.340000,26.326000,...,318.991000,10.390000,19.600000,40.900000,83.741000,4.200000,79.380000,0.847000,64.83,4.980000e-01
max,4.615654e+07,545816.000000,482844.00000,1.196272e+06,1237.550828,10491.000000,7456.857000,61554.391000,8652.658000,2472.188000,...,1803.987000,30.530000,597.029000,78.100000,98.999000,13.800000,86.750000,0.953000,64.83,4.980000e-01

In [26]:
locationvars = ['iso_code', 'continent', 'location', 'gdp_per_capita', 'hospital_beds_per_thousand']

In [27]:
df_OWID_COVID_Global[locationvars].isnull().sum(axis=0)

iso_code                       307
continent                      614
location                         0
gdp_per_capita                5951
hospital_beds_per_thousand    7619
dtype: int64

# Test code for finding missing data

In [28]:
if using_Google_colab:
  covidtotals = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/TestFolder/COVIDTotalswithmissings.csv')
if using_Anaconda_on_Mac_or_Linux:
  covidtotals = pd.read_csv("../input/TestFolder/covidtotalswithmissings.csv")
if using_Anaconda_on_windows:
  covidtotals = pd.read_csv(r"..\input\TestFolder\covidtotalswithmissings.csv")
covidtotals

,iso_code,lastdate,location,total_cases,total_deaths,total_cases_pm,total_deaths_pm,population,pop_density,median_age,gdp_per_capita,hosp_beds
0,AFG,6/1/20,Afghanistan,15205,257,390.589,6.602,38928341,54.422,18.6,1803.987,0.50
1,ALB,6/1/20,Albania,1137,33,395.093,11.467,2877800,104.871,38.0,11803.431,2.89
2,DZA,6/1/20,Algeria,9394,653,214.225,14.891,43851043,17.348,29.1,13913.839,1.90
3,AND,6/1/20,Andorra,764,51,9888.048,660.066,77265,163.755,NaN,NaN,NaN
4,AGO,6/1/20,Angola,86,4,2.617,0.122,32866268,23.890,16.8,5819.495,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
205,VNM,6/1/20,Vietnam,328,0,3.370,0.000,97338583,308.127,32.6,6171.884,2.60
206,ESH,6/1/20,Western Sahara,23,1,38.505,1.674,597330,NaN,28.4,NaN,NaN
207,YEM,6/1/20,Yemen,323,80,10.829,2.682,29825968,53.508,20.3,1479.147,0.70
208,ZMB,6/1/20,Zambia,1057,7,57.496,0.381,18383956,22.995,17.7,3689.251,2.00
209,ZWE,6/1/20,Zimbabwe,178,4,11.976,0.269,14862927,42.729,19.6,1899.775,1.70

In [29]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']

In [30]:
demovars = ['population','pop_density','median_age','gdp_per_capita','hosp_beds']

In [31]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [32]:
demovarsmisscnt = covidtotals[demovars].isnull().sum(axis=1)

In [33]:
demovarsmisscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
dtype: int64