In [1]:
import pandas as pd
from datetime import date

In [2]:
using_Google_colab = True
using_Anaconda_on_Mac_or_Linux = False
using_Anaconda_on_windows = False

In [3]:
if using_Google_colab:
    from google.colab import drive
    drive.mount('/content/drive')

Mounted at /content/drive

Data Prep for USA_Facts confirmed cases at county level

Read file

In [4]:
if using_Google_colab:
    df_confirmed_cases = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/USA_Facts/covid_confirmed_usafacts.csv')
if using_Anaconda_on_Mac_or_Linux:
    df_confirmed_cases = pd.read_csv('../input/USA_Facts/covid_confirmed_usafacts.csv')
if using_Anaconda_on_windows:
    df_confirmed_cases = pd.read_csv(r'..\input\USA_Facts\covid_confirmed_usafacts.csv') 
df_confirmed_cases = df_confirmed_cases.astype({'countyFIPS': str}).astype({'stateFIPS': str})
df_confirmed_cases

     countyFIPS            County Name State  ... 12/18/20  12/19/20  12/20/20
0             0  Statewide Unallocated    AL  ...        0         0         0
1          1001         Autauga County    AL  ...     3647      3698      3741
2          1003         Baldwin County    AL  ...    11556     11722     11827
3          1005         Barbour County    AL  ...     1318      1330      1336
4          1007            Bibb County    AL  ...     1577      1601      1613
...         ...                    ...   ...  ...      ...       ...       ...
3190      56037      Sweetwater County    WY  ...     2696      2702      2718
3191      56039           Teton County    WY  ...     1990      1992      2002
3192      56041           Uinta County    WY  ...     1399      1406      1416
3193      56043        Washakie County    WY  ...      690       695       699
3194      56045          Weston County    WY  ...      443       443       446

[3195 rows x 338 columns]

Now I need to transpose so all dates are in rows

In [5]:
df_confirmed_cases_by_county_by_date = df_confirmed_cases.melt(id_vars=['County Name',
                                                                        'countyFIPS', 
                                                                        'State', 
                                                                        'stateFIPS'], 
                                                               var_name='Date', 
                                                               value_name='Total Cases')
df_confirmed_cases_by_county_by_date

                   County Name countyFIPS  ...      Date Total Cases
0        Statewide Unallocated          0  ...   1/22/20           0
1               Autauga County       1001  ...   1/22/20           0
2               Baldwin County       1003  ...   1/22/20           0
3               Barbour County       1005  ...   1/22/20           0
4                  Bibb County       1007  ...   1/22/20           0
...                        ...        ...  ...       ...         ...
1067125      Sweetwater County      56037  ...  12/20/20        2718
1067126           Teton County      56039  ...  12/20/20        2002
1067127           Uinta County      56041  ...  12/20/20        1416
1067128        Washakie County      56043  ...  12/20/20         699
1067129          Weston County      56045  ...  12/20/20         446

[1067130 rows x 6 columns]

In [6]:
df_confirmed_cases_by_county_by_date = df_confirmed_cases_by_county_by_date.astype({'Date': 'datetime64[ns]'})
df_sorted_confirmed_cases = df_confirmed_cases_by_county_by_date.sort_values(by=['countyFIPS','Date'])
df_sorted_confirmed_cases

                   County Name countyFIPS  ...       Date Total Cases
0        Statewide Unallocated          0  ... 2020-01-22           0
68       Statewide Unallocated          0  ... 2020-01-22           0
99       Statewide Unallocated          0  ... 2020-01-22           0
115      Statewide Unallocated          0  ... 2020-01-22           0
191      Statewide Unallocated          0  ... 2020-01-22           0
...                        ...        ...  ...        ...         ...
1051479         Windham County       9015  ... 2020-12-16        3921
1054674         Windham County       9015  ... 2020-12-17        3998
1057869         Windham County       9015  ... 2020-12-18        4153
1061064         Windham County       9015  ... 2020-12-19        4153
1064259         Windham County       9015  ... 2020-12-20        4153

[1067130 rows x 6 columns]

Now shift by one to get previous day cases and compute incremental cases

In [7]:
df_sorted_confirmed_cases['Inc_Cases'] = df_sorted_confirmed_cases.groupby('countyFIPS')['Total Cases'].apply(
    lambda x: x - x.shift(1))
df_sorted_confirmed_cases

                   County Name countyFIPS  ... Total Cases Inc_Cases
0        Statewide Unallocated          0  ...           0       NaN
68       Statewide Unallocated          0  ...           0       0.0
99       Statewide Unallocated          0  ...           0       0.0
115      Statewide Unallocated          0  ...           0       0.0
191      Statewide Unallocated          0  ...           0       0.0
...                        ...        ...  ...         ...       ...
1051479         Windham County       9015  ...        3921     130.0
1054674         Windham County       9015  ...        3998      77.0
1057869         Windham County       9015  ...        4153     155.0
1061064         Windham County       9015  ...        4153       0.0
1064259         Windham County       9015  ...        4153       0.0

[1067130 rows x 7 columns]

Now compute 7 days rolling average

In [8]:
df_sorted_confirmed_cases['cases_moving_avg'] = df_sorted_confirmed_cases.groupby('countyFIPS')['Inc_Cases'].apply(
    lambda x: (x + x.shift(1) + x.shift(2) + x.shift(3) + x.shift(4) + x.shift(5) + x.shift(6))/7)
df_sorted_confirmed_cases

                   County Name countyFIPS  ... Inc_Cases cases_moving_avg
0        Statewide Unallocated          0  ...       NaN              NaN
68       Statewide Unallocated          0  ...       0.0              NaN
99       Statewide Unallocated          0  ...       0.0              NaN
115      Statewide Unallocated          0  ...       0.0              NaN
191      Statewide Unallocated          0  ...       0.0              NaN
...                        ...        ...  ...       ...              ...
1051479         Windham County       9015  ...     130.0        90.142857
1054674         Windham County       9015  ...      77.0        90.285714
1057869         Windham County       9015  ...     155.0       103.714286
1061064         Windham County       9015  ...       0.0       103.714286
1064259         Windham County       9015  ...       0.0       103.714286

[1067130 rows x 8 columns]

In [9]:
def direction_of_spread(x):
    if x['Inc Cases'] > x['moving_avg']: 
        return 'increasing'
    else: 
        return'decreasing'

In [10]:
df_sorted_confirmed_cases['difference'] = df_sorted_confirmed_cases['Inc_Cases'] - df_sorted_confirmed_cases[
    'cases_moving_avg']
df_sorted_confirmed_cases['direction']=df_sorted_confirmed_cases['difference'].apply(
    lambda x: 'increasing' if x>0 else 'not increasing')
df_sorted_confirmed_cases[df_sorted_confirmed_cases['State'] == 'NY']

                   County Name countyFIPS  ... difference       direction
1861     Statewide Unallocated          0  ...   0.000000  not increasing
5056     Statewide Unallocated          0  ...   0.000000  not increasing
8251     Statewide Unallocated          0  ...   0.000000  not increasing
11446    Statewide Unallocated          0  ...   0.000000  not increasing
14641    Statewide Unallocated          0  ...   0.000000  not increasing
...                        ...        ...  ...        ...             ...
1053079           Yates County      36123  ...  -2.714286  not increasing
1056274           Yates County      36123  ...   2.142857      increasing
1059469           Yates County      36123  ...   2.857143      increasing
1062664           Yates County      36123  ...  -3.000000  not increasing
1065859           Yates County      36123  ...  -1.714286  not increasing

[21376 rows x 10 columns]

In [12]:
if using_Google_colab:
    df_sorted_confirmed_cases.to_csv('/content/drive/MyDrive/COVID_Project/output/confirmed_cases_by_county.csv')
if using_Anaconda_on_Mac_or_Linux:
    df_sorted_confirmed_cases.to_csv('../output/confirmed_cases_by_county.csv')
if using_Anaconda_on_windows:
    df_sorted_confirmed_cases.to_csv('..\output\confirmed_cases_by_county.csv')

Data prep for COVID deaths by County

Read file

In [13]:
if using_Google_colab:
    df_covid_deaths = pd.read_csv('/content/drive/MyDrive/COVID_Project/input/USA_Facts/covid_deaths_usafacts.csv')
if using_Anaconda_on_Mac_or_Linux:
    df_covid_deaths = pd.read_csv('../input/USA_Facts/covid_deaths_usafacts.csv')
if using_Anaconda_on_windows:
    df_covid_deaths = pd.read_csv(r'..\input\USA_Facts\covid_deaths_usafacts.csv') 
df_covid_deaths = df_covid_deaths.astype({'countyFIPS': str}).astype({'stateFIPS': str})
df_covid_deaths

     countyFIPS            County Name State  ... 12/18/20  12/19/20  12/20/20
0             0  Statewide Unallocated    AL  ...        0         0         0
1          1001         Autauga County    AL  ...       44        44        44
2          1003         Baldwin County    AL  ...      146       147       147
3          1005         Barbour County    AL  ...       30        32        32
4          1007            Bibb County    AL  ...       42        42        42
...         ...                    ...   ...  ...      ...       ...       ...
3190      56037      Sweetwater County    WY  ...       15        15        15
3191      56039           Teton County    WY  ...        2         2         2
3192      56041           Uinta County    WY  ...        7         7         7
3193      56043        Washakie County    WY  ...       11        11        11
3194      56045          Weston County    WY  ...        2         2         2

[3195 rows x 338 columns]

Now group the data by State

Now I need to transpose so all dates are in rows

In [14]:
df_covid_deaths_by_county_by_date = df_covid_deaths.melt(id_vars=['State',
                                                                  'stateFIPS', 
                                                                  'County Name', 
                                                                  'countyFIPS'], 
                                                         var_name='Date', 
                                                         value_name='Total Deaths')
df_covid_deaths_by_county_by_date

        State stateFIPS  ...      Date Total Deaths
0          AL         1  ...   1/22/20            0
1          AL         1  ...   1/22/20            0
2          AL         1  ...   1/22/20            0
3          AL         1  ...   1/22/20            0
4          AL         1  ...   1/22/20            0
...       ...       ...  ...       ...          ...
1067125    WY        56  ...  12/20/20           15
1067126    WY        56  ...  12/20/20            2
1067127    WY        56  ...  12/20/20            7
1067128    WY        56  ...  12/20/20           11
1067129    WY        56  ...  12/20/20            2

[1067130 rows x 6 columns]

In [15]:
df_covid_deaths_by_county_by_date = df_covid_deaths_by_county_by_date.astype({'Date': 'datetime64[ns]'})
df_sorted_covid_deaths = df_covid_deaths_by_county_by_date.sort_values(by=['countyFIPS', 'Date'])
df_sorted_covid_deaths

        State stateFIPS  ...       Date Total Deaths
0          AL         1  ... 2020-01-22            0
68         AK         2  ... 2020-01-22            0
99         AZ         4  ... 2020-01-22            0
115        AR         5  ... 2020-01-22            0
191        CA         6  ... 2020-01-22            0
...       ...       ...  ...        ...          ...
1051479    CT         9  ... 2020-12-16           48
1054674    CT         9  ... 2020-12-17           51
1057869    CT         9  ... 2020-12-18           51
1061064    CT         9  ... 2020-12-19           51
1064259    CT         9  ... 2020-12-20           51

[1067130 rows x 6 columns]

Now shift by one to get previous day deaths and compute incremental deaths

In [16]:
df_sorted_covid_deaths['Inc Deaths'] = df_sorted_covid_deaths.groupby('countyFIPS')['Total Deaths'].apply(
    lambda x: x - x.shift(1))
df_sorted_covid_deaths

        State stateFIPS  ... Total Deaths Inc Deaths
0          AL         1  ...            0        NaN
68         AK         2  ...            0        0.0
99         AZ         4  ...            0        0.0
115        AR         5  ...            0        0.0
191        CA         6  ...            0        0.0
...       ...       ...  ...          ...        ...
1051479    CT         9  ...           48        2.0
1054674    CT         9  ...           51        3.0
1057869    CT         9  ...           51        0.0
1061064    CT         9  ...           51        0.0
1064259    CT         9  ...           51        0.0

[1067130 rows x 7 columns]

Now compute 7 days rolling average

In [17]:
df_sorted_covid_deaths['death moving_avg'] = df_sorted_covid_deaths.groupby('countyFIPS')['Inc Deaths'].apply(
    lambda x: (x + x.shift(1) + x.shift(2) + x.shift(3) + x.shift(4) + x.shift(5) + x.shift(6))/7)
df_sorted_covid_deaths

        State stateFIPS  ... Inc Deaths death moving_avg
0          AL         1  ...        NaN              NaN
68         AK         2  ...        0.0              NaN
99         AZ         4  ...        0.0              NaN
115        AR         5  ...        0.0              NaN
191        CA         6  ...        0.0              NaN
...       ...       ...  ...        ...              ...
1051479    CT         9  ...        2.0         1.714286
1054674    CT         9  ...        3.0         1.571429
1057869    CT         9  ...        0.0         1.285714
1061064    CT         9  ...        0.0         1.285714
1064259    CT         9  ...        0.0         1.285714

[1067130 rows x 8 columns]

In [18]:
if using_Google_colab:
    df_sorted_covid_deaths.to_csv('/content/drive/MyDrive/COVID_Project/output/covid_deaths_by_county.csv')
if using_Anaconda_on_Mac_or_Linux:
    df_sorted_covid_deaths.to_csv('../output/covid_deaths_by_county.csv')
if using_Anaconda_on_windows:
    df_sorted_covid_deaths.to_csv(r'..\output\covid_deaths_by_county.csv')

Create partial analytics_base_table with confirmed cases and deaths

In [19]:
df_partial_abt_by_county = pd.merge(df_sorted_confirmed_cases, df_sorted_covid_deaths, 
                                    on=['countyFIPS', 'Date'], 
                                    suffixes=('', '_DROP'), 
                                    how='inner').filter(regex='^(?!.*_DROP)')
df_partial_abt_by_county

                   County Name countyFIPS  ... Inc Deaths death moving_avg
0        Statewide Unallocated          0  ...        NaN              NaN
1        Statewide Unallocated          0  ...        0.0              NaN
2        Statewide Unallocated          0  ...        0.0              NaN
3        Statewide Unallocated          0  ...        0.0              NaN
4        Statewide Unallocated          0  ...        0.0              NaN
...                        ...        ...  ...        ...              ...
1885425         Windham County       9015  ...        2.0         1.714286
1885426         Windham County       9015  ...        3.0         1.571429
1885427         Windham County       9015  ...        0.0         1.285714
1885428         Windham County       9015  ...        0.0         1.285714
1885429         Windham County       9015  ...        0.0         1.285714

[1885430 rows x 13 columns]

In [20]:
df_partial_abt_by_county[df_partial_abt_by_county['County Name'] == 'Los Angeles County'].count()

County Name         334
countyFIPS          334
State               334
stateFIPS           334
Date                334
Total Cases         334
Inc_Cases           333
cases_moving_avg    327
difference          327
direction           334
Total Deaths        334
Inc Deaths          333
death moving_avg    327
dtype: int64

In [21]:
df_partial_abt_by_county[df_partial_abt_by_county['County Name'] == 'Los Angeles County'].Date.min()

Timestamp('2020-01-22 00:00:00')

In [22]:
df_partial_abt_by_county[df_partial_abt_by_county['County Name'] == 'Los Angeles County'].Date.max()

Timestamp('2020-12-20 00:00:00')