In [1]:
import os
import pandas as pd

In [2]:
using_Google_colab = False
using_Anaconda_on_Mac_or_Linux = True
using_Anaconda_on_windows = False

In [3]:
if using_Google_colab:
    from google.colab import drive
    drive.mount('/content/drive')

In [4]:
if using_Google_colab:
    dir_input = "/content/drive/MyDrive/COVID_Project/input"
if using_Anaconda_on_Mac_or_Linux:
    dir_input = "../input"
if using_Anaconda_on_windows:
    dir_input = r"..\input"

# PD 1.1 and PD 2.1 Open Notebook titled “Select_and_filter_operation”

Read file

In [5]:
df_google_mobility_data = pd.read_csv(os.path.join(dir_input, 
                                                   "Google", 
                                                   "Region_Mobility_Report_CSVs", 
                                                   "2020_US_Region_Mobility_Report.csv"))
df_google_mobility_data

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796331,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-12-18,NaN,NaN,NaN,NaN,-17.0,NaN
796332,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-12-21,NaN,NaN,NaN,NaN,-39.0,NaN
796333,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-12-22,NaN,NaN,NaN,NaN,-38.0,NaN
796334,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-12-23,NaN,NaN,NaN,NaN,-48.0,NaN
796335,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN

In [6]:
df_google_mobility_data.columns

Index(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2',
       'metro_area', 'iso_3166_2_code', 'census_fips_code', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'],
      dtype='object')

Select 'sub_region_1','census_fips_code', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'

In [7]:
df_google_mobility_data_selected = df_google_mobility_data[['sub_region_1','census_fips_code', 'date',
                                                             'retail_and_recreation_percent_change_from_baseline',
                                                             'grocery_and_pharmacy_percent_change_from_baseline',
                                                             'parks_percent_change_from_baseline',
                                                             'transit_stations_percent_change_from_baseline',
                                                             'workplaces_percent_change_from_baseline',
                                                             'residential_percent_change_from_baseline']]
                                              
df_google_mobility_data_selected

,sub_region_1,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
796331,Wyoming,56045.0,2020-12-18,NaN,NaN,NaN,NaN,-17.0,NaN
796332,Wyoming,56045.0,2020-12-21,NaN,NaN,NaN,NaN,-39.0,NaN
796333,Wyoming,56045.0,2020-12-22,NaN,NaN,NaN,NaN,-38.0,NaN
796334,Wyoming,56045.0,2020-12-23,NaN,NaN,NaN,NaN,-48.0,NaN
796335,Wyoming,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN

In [8]:
df_google_mobility_data_selected = df_google_mobility_data_selected.rename(columns={"census_fips_code": "countyFIPS"})
df_google_mobility_data_selected

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
796331,Wyoming,56045.0,2020-12-18,NaN,NaN,NaN,NaN,-17.0,NaN
796332,Wyoming,56045.0,2020-12-21,NaN,NaN,NaN,NaN,-39.0,NaN
796333,Wyoming,56045.0,2020-12-22,NaN,NaN,NaN,NaN,-38.0,NaN
796334,Wyoming,56045.0,2020-12-23,NaN,NaN,NaN,NaN,-48.0,NaN
796335,Wyoming,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN

In [9]:
df_google_mobility_data_selected.columns

Index(['sub_region_1', 'countyFIPS', 'date',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'],
      dtype='object')

# PD2.2 Start with the DataFrame you created in the previous section.  Select data for 24th December

In [10]:
df_christmas_eve = df_google_mobility_data_selected[df_google_mobility_data_selected.date == "2020-12-24"]
df_christmas_eve

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
313,NaN,NaN,2020-12-24,-16.0,27.0,-21.0,-43.0,-61.0,16.0
628,Alabama,NaN,2020-12-24,-12.0,34.0,-28.0,-25.0,-63.0,17.0
937,Alabama,1001.0,2020-12-24,-2.0,48.0,NaN,NaN,-66.0,17.0
1252,Alabama,1003.0,2020-12-24,-14.0,31.0,-27.0,-34.0,-60.0,13.0
1542,Alabama,1005.0,2020-12-24,7.0,NaN,NaN,NaN,-56.0,NaN
...,...,...,...,...,...,...,...,...,...
795333,Wyoming,56037.0,2020-12-24,-14.0,NaN,NaN,-21.0,-55.0,13.0
795623,Wyoming,56039.0,2020-12-24,-29.0,NaN,0.0,-37.0,-49.0,NaN
795913,Wyoming,56041.0,2020-12-24,5.0,NaN,NaN,-10.0,-53.0,12.0
796127,Wyoming,56043.0,2020-12-24,NaN,NaN,NaN,NaN,-47.0,NaN
796335,Wyoming,56045.0,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN

In [11]:
df_christmas_eve[df_christmas_eve.retail_and_recreation_percent_change_from_baseline > 30.0]

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
74207,Colorado,8083.0,2020-12-24,31.0,NaN,NaN,NaN,-50.0,13.0
397694,Missouri,29109.0,2020-12-24,32.0,NaN,NaN,-27.0,-53.0,11.0
410181,Missouri,29213.0,2020-12-24,39.0,88.0,-26.0,NaN,-41.0,6.0
634114,Tennessee,47155.0,2020-12-24,35.0,63.0,118.0,NaN,-43.0,10.0

In [12]:
df_google_mobility_data_selected = df_google_mobility_data_selected.dropna(subset=['countyFIPS'])
df_google_mobility_data_selected = df_google_mobility_data_selected.astype({'countyFIPS': int})
df_google_mobility_data_selected = df_google_mobility_data_selected.astype({'countyFIPS': str})
df_google_mobility_data_selected

,sub_region_1,countyFIPS,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
630,Alabama,1001,2020-02-15,5.0,7.0,NaN,NaN,-4.0,NaN
631,Alabama,1001,2020-02-16,0.0,1.0,-23.0,NaN,-4.0,NaN
632,Alabama,1001,2020-02-17,8.0,0.0,NaN,NaN,-27.0,5.0
633,Alabama,1001,2020-02-18,-2.0,0.0,NaN,NaN,2.0,0.0
634,Alabama,1001,2020-02-19,-2.0,0.0,NaN,NaN,2.0,0.0
...,...,...,...,...,...,...,...,...,...
796331,Wyoming,56045,2020-12-18,NaN,NaN,NaN,NaN,-17.0,NaN
796332,Wyoming,56045,2020-12-21,NaN,NaN,NaN,NaN,-39.0,NaN
796333,Wyoming,56045,2020-12-22,NaN,NaN,NaN,NaN,-38.0,NaN
796334,Wyoming,56045,2020-12-23,NaN,NaN,NaN,NaN,-48.0,NaN
796335,Wyoming,56045,2020-12-24,NaN,NaN,NaN,NaN,-56.0,NaN